# Generated by Django 2.2.4 on 2019-09-08 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PadServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('url', models.URLField(max_length=256, verbose_name='URL')),
                ('apikey', models.CharField(max_length=256, verbose_name='API key')),
                ('notes', models.TextField(blank=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'server',
            },
        ),
        migrations.CreateModel(
            name='PadGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupID', models.CharField(blank=True, max_length=256)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auth.Group')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='py_etherpadlite.PadServer')),
            ],
            options={
                'verbose_name': 'group',
            },
        ),
        migrations.CreateModel(
            name='PadAuthor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authorID', models.CharField(blank=True, max_length=256)),
                ('group', models.ManyToManyField(blank=True, null=True, related_name='authors', to='py_etherpadlite.PadGroup')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='py_etherpadlite.PadServer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'author',
            },
        ),
        migrations.CreateModel(
            name='Pad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='py_etherpadlite.PadGroup')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='py_etherpadlite.PadServer')),
            ],
        ),
    ]
