# Generated by Django 2.2.4 on 2019-09-10 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('py_etherpadlite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='padauthor',
            name='group',
            field=models.ManyToManyField(blank=True, related_name='authors', to='py_etherpadlite.PadGroup'),
        ),
    ]
