# Generated by Django 2.2.4 on 2019-09-21 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('py_etherpadlite', '0002_auto_20190910_1109'),
        ('live_collaboration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstate',
            name='pad',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='py_etherpadlite.Pad'),
        ),
    ]
